/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceResumeRouteImport } from './routes/voice-resume'
import { Route as MapRouteImport } from './routes/map'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'

const VoiceResumeRoute = VoiceResumeRouteImport.update({
  id: '/voice-resume',
  path: '/voice-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/employer': typeof EmployerRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/map': typeof MapRoute
  '/voice-resume': typeof VoiceResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/employer': typeof EmployerRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/map': typeof MapRoute
  '/voice-resume': typeof VoiceResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/employer': typeof EmployerRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/map': typeof MapRoute
  '/voice-resume': typeof VoiceResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/employer'
    | '/interview'
    | '/jobs'
    | '/map'
    | '/voice-resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/employer'
    | '/interview'
    | '/jobs'
    | '/map'
    | '/voice-resume'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/employer'
    | '/interview'
    | '/jobs'
    | '/map'
    | '/voice-resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  EmployerRoute: typeof EmployerRoute
  InterviewRoute: typeof InterviewRoute
  JobsRoute: typeof JobsRoute
  MapRoute: typeof MapRoute
  VoiceResumeRoute: typeof VoiceResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-resume': {
      id: '/voice-resume'
      path: '/voice-resume'
      fullPath: '/voice-resume'
      preLoaderRoute: typeof VoiceResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  EmployerRoute: EmployerRoute,
  InterviewRoute: InterviewRoute,
  JobsRoute: JobsRoute,
  MapRoute: MapRoute,
  VoiceResumeRoute: VoiceResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
